## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
required = []

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
ignored = []

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
[[constraint]]
## Required: the root import path of the project being constrained.
name = "github.com/timtadh/data-structures"

## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
version = "0.5.0"
# branch = "master"
# revision = "abc123"

## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"
